-- AlterTable
ALTER TABLE `Log` MODIFY `status` ENUM('DRAFT', 'PROCESSING', 'REVISION', 'TECH_CONFIRMATION', 'TECH_REVISION', 'NEED_SIGNATURE', 'ENROLLED', 'REFUSED_TO_SIGN', 'REFUSED_TO_ENROLL', 'REJECTED', 'REPROCESSING') NOT NULL;
